services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: keycloak-server
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - ./containers/identity:/opt/keycloak/data
    user: root